//! The route in the shapes a simulator's own flight-plan importer reads: the MSFS
//! `.pln`, the X-Plane `.fms` (version 1100), a PMDG-style `.rte`, an ICAO flight plan
//! message (Doc 4444 Appendix 2), and the whole `Dispatch` as JSON.
//!
//! No installed copy of the PMDG 737/777, the FlyByWire or iniBuilds aircraft, or MSFS
//! itself was on the machine this was written on to check a real file against (only the
//! Synaptic A220 was, and it reads SimBrief rather than a route file). The `.pln` and
//! `.fms` writers follow formats that have been the same and openly documented since FSX
//! and X-Plane 10 respectively, which is as close to verified as this machine allows;
//! `.rte` is PMDG's own format and unverified — see the final report.

use crate::dispatch::{Dispatch, PointKind, Waypoint};
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::path::Path;

fn write_file(out: &Path, contents: &str) -> Result<u64> {
    if let Some(parent) = out.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(out, contents).with_context(|| format!("write {}", out.display()))?;
    Ok(contents.len() as u64)
}

/// Degrees, minutes and hundredths of a second, the way the `.pln` LLA fields write a
/// coordinate: `N38° 46' 52.68"`.
fn dms(value: f64, pos: char, neg: char) -> String {
    let hemi = if value >= 0.0 { pos } else { neg };
    let a = value.abs();
    let deg = a.floor();
    let min_f = (a - deg) * 60.0;
    let min = min_f.floor();
    let sec = (min_f - min) * 60.0;
    format!("{hemi}{deg:.0}° {min:.0}' {sec:.2}\"")
}

fn lla(lat: f64, lon: f64, alt_m: f64) -> String {
    format!("{},{},{:+011.2}", dms(lat, 'N', 'S'), dms(lon, 'E', 'W'), alt_m)
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

fn waypoint_type(kind: PointKind) -> &'static str {
    match kind {
        PointKind::Airport => "Airport",
        PointKind::Sid | PointKind::Star | PointKind::Approach => "Intersection",
        PointKind::Enroute | PointKind::Track => "Intersection",
    }
}

// ---------------------------------------------------------------------------------
// MSFS .pln
// ---------------------------------------------------------------------------------

/// A Microsoft Flight Simulator flight plan, the `AceXML`/`SimBase.Document` shape FSX
/// introduced and MSFS 2020/2024 still read.
pub fn pln(d: &Dispatch) -> String {
    let o = &d.route.origin;
    let dest = &d.route.destination;
    let mut s = String::new();
    let _ = writeln!(s, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    let _ = writeln!(s, "<SimBase.Document Type=\"AceXML\" version=\"1,0\">");
    let _ = writeln!(s, "  <Descr>AceXML Document</Descr>");
    let _ = writeln!(s, "  <FlightPlan.FlightPlan>");
    let _ = writeln!(s, "    <Title>{} to {}</Title>", o.icao, dest.icao);
    let _ = writeln!(s, "    <FPType>IFR</FPType>");
    let _ = writeln!(s, "    <RouteType>HighAlt</RouteType>");
    let _ = writeln!(s, "    <CruisingAlt>{:.0}</CruisingAlt>", d.route.cruise_ft);
    let _ = writeln!(s, "    <DepartureID>{}</DepartureID>", o.icao);
    let _ = writeln!(s, "    <DepartureLLA>{}</DepartureLLA>", lla(o.pos.0, o.pos.1, o.elevation_ft * 0.3048));
    let _ = writeln!(s, "    <DestinationID>{}</DestinationID>", dest.icao);
    let _ = writeln!(s, "    <DestinationLLA>{}</DestinationLLA>", lla(dest.pos.0, dest.pos.1, dest.elevation_ft * 0.3048));
    let _ = writeln!(s, "    <Descr>generated by amdbgen</Descr>");
    let _ = writeln!(s, "    <DepartureName>{}</DepartureName>", xml_escape(&o.name));
    let _ = writeln!(s, "    <DestinationName>{}</DestinationName>", xml_escape(&dest.name));
    for w in &d.route.points {
        waypoint_xml(&mut s, w);
    }
    let _ = writeln!(s, "  </FlightPlan.FlightPlan>");
    let _ = writeln!(s, "</SimBase.Document>");
    s
}

fn waypoint_xml(s: &mut String, w: &Waypoint) {
    let _ = writeln!(s, "    <ATCWaypoint id=\"{}\">", xml_escape(&w.ident));
    let _ = writeln!(s, "      <ATCWaypointType>{}</ATCWaypointType>", waypoint_type(w.kind));
    let _ = writeln!(s, "      <WorldPosition>{}</WorldPosition>", lla(w.pos.0, w.pos.1, 0.0));
    if matches!(w.kind, PointKind::Airport) {
        let _ = writeln!(s, "      <ICAO>");
        let _ = writeln!(s, "        <ICAOIdent>{}</ICAOIdent>", xml_escape(&w.ident));
        let _ = writeln!(s, "      </ICAO>");
    }
    let _ = writeln!(s, "    </ATCWaypoint>");
}

pub fn write_pln(d: &Dispatch, out: &Path) -> Result<u64> {
    write_file(out, &pln(d))
}

// ---------------------------------------------------------------------------------
// X-Plane .fms (version 1100)
// ---------------------------------------------------------------------------------

/// An X-Plane flight plan, format 1100: the shape `Aircraft/.../FMS plans/*.fms` has had
/// since X-Plane 10, and what the FMS and every third-party FMC reads today.
pub fn fms(d: &Dispatch) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "I");
    let _ = writeln!(s, "1100 Version");
    let _ = writeln!(s, "CYCLE {}", d.airac.as_deref().unwrap_or("0000"));
    let _ = writeln!(s, "ADEP {}", d.route.origin.icao);
    if let Some(rwy) = &d.route.dep_runway {
        let _ = writeln!(s, "DEPRWY RW{rwy}");
    }
    let _ = writeln!(s, "ADES {}", d.route.destination.icao);
    if let Some(rwy) = &d.route.arr_runway {
        let _ = writeln!(s, "DESRWY RW{rwy}");
    }
    let _ = writeln!(s, "NUMENR {}", d.route.points.len());
    for w in &d.route.points {
        let (kind, name) = fms_row(w);
        let _ = writeln!(s, "{kind} {name} {name} {:.0} {:.6} {:.6}", w.alt_max_ft.or(w.alt_min_ft).unwrap_or(d.route.cruise_ft), w.pos.0, w.pos.1);
    }
    s
}

/// X-Plane's type codes: 1 airport, 3 VOR, 2 NDB, 11 a plain fix/waypoint. Nothing this
/// crate carries tells a waypoint from a VOR or an NDB by name alone, so every point that
/// is not an airport is written as a fix, which the FMS accepts and flies exactly as a
/// direct or airway leg either way.
fn fms_row(w: &Waypoint) -> (u8, &str) {
    match w.kind {
        PointKind::Airport => (1, w.ident.as_str()),
        _ => (11, w.ident.as_str()),
    }
}

pub fn write_fms(d: &Dispatch, out: &Path) -> Result<u64> {
    write_file(out, &fms(d))
}

// ---------------------------------------------------------------------------------
// PMDG .rte — best effort; see the module note above.
// ---------------------------------------------------------------------------------

/// A route file in the plain shape PMDG's older NGX/CoRte tooling documented for the 737
/// and 777: a header naming the ends, then the route string and every waypoint with its
/// position. Not checked against a real PMDG install — none was on this machine — so
/// treat it as a starting point, not a guarantee the tablet's importer reads it.
pub fn rte(d: &Dispatch) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "; PMDG route file, written by amdbgen (unverified format — see the final report)");
    let _ = writeln!(s, "ORIGIN {}", d.route.origin.icao);
    let _ = writeln!(s, "DEST {}", d.route.destination.icao);
    if let Some(alt) = &d.alternate {
        let _ = writeln!(s, "ALTN {}", alt.destination.icao);
    }
    let _ = writeln!(s, "CRZALT {:.0}", d.route.cruise_ft);
    let _ = writeln!(s, "ROUTE {}", d.route.route_string());
    let _ = writeln!(s, "NUMWPT {}", d.route.points.len());
    for w in &d.route.points {
        let _ = writeln!(s, "{},{:.6},{:.6},{}", w.ident, w.pos.0, w.pos.1, w.via);
    }
    s
}

pub fn write_rte(d: &Dispatch, out: &Path) -> Result<u64> {
    write_file(out, &rte(d))
}

// ---------------------------------------------------------------------------------
// ICAO flight plan message (Doc 4444, Appendix 2).
// ---------------------------------------------------------------------------------

/// The wake-turbulence category letter ICAO's item 9 wants, from maximum take-off mass.
fn wake_category(mtow_kg: f64) -> char {
    if mtow_kg > 136_000.0 {
        'H'
    } else if mtow_kg >= 7_000.0 {
        'M'
    } else {
        'L'
    }
}

/// The ICAO flight plan message: item 7 through item 19, as it would be filed. `PBN`,
/// `DOF` and `REG` go in item 18 where they are known; item 19's emergency equipment is
/// left at the generic default, since none of it is a `dispatch::AircraftSpec` field.
pub fn icao_message(d: &Dispatch, flight_number: Option<&str>, registration: Option<&str>) -> String {
    let callsign = flight_number.unwrap_or(&d.spec.icao_type).to_string();
    let wake = wake_category(d.spec.mtow_kg);
    let level = format!("F{:03.0}", d.route.cruise_ft / 100.0);
    let speed = format!("N{:04.0}", d.perf.profile.first().map(|p| p.tas_kt).filter(|t| *t > 0.0).unwrap_or_else(|| tas_estimate(d)));
    let eet = d.perf.profile.last().map(|p| p.time_min).unwrap_or(0.0);
    let alt = d.alternate.as_ref().map(|a| a.destination.icao.as_str()).unwrap_or("----");
    let mut s = String::new();
    let _ = write!(s, "(FPL-{callsign}-IG");
    let _ = write!(s, "\n-1/{}/{wake}-SDE2E3FGHIRWXY/LB1", d.spec.icao_type);
    let _ = write!(s, "\n-{} {}", d.route.origin.icao, d.route.off_block.format("%H%M"));
    let _ = write!(s, "\n-{speed}{level} {}", d.route.route_string());
    let _ = write!(s, "\n-{} {:02}{:02} {alt}", d.route.destination.icao, (eet / 60.0) as u32, (eet.round() as i64).rem_euclid(60));
    let _ = write!(s, "\n-PBN/A1B1C1D1O1S2 DOF/{}", d.route.off_block.format("%y%m%d"));
    if let Some(r) = registration {
        let _ = write!(s, " REG/{}", r.replace('-', ""));
    }
    let endurance_min = d.perf.fuel.block_kg.max(1.0) / (d.perf.fuel.trip_kg.max(1.0) / eet.max(1.0)) - eet;
    let _ = write!(s, "\n-E/{:02}{:02} P/TBN", (endurance_min.max(0.0) / 60.0) as u32, (endurance_min.max(0.0).round() as i64).rem_euclid(60));
    let _ = write!(s, "\n R/UVE S/M J/L D/1 1 A/YELLOW C/AMDBGEN)");
    s
}

/// A rough true airspeed at cruise, in knots, when the performance model did not run: the
/// same estimate `ofp::dispatch`'s fallback cost model uses.
fn tas_estimate(d: &Dispatch) -> f64 {
    let t_kelvin = crate::dispatch::isa_temp_c(d.route.cruise_ft) + 273.15;
    d.spec.cruise_mach.max(0.5) * 38.967_854 * t_kelvin.sqrt()
}

pub fn write_icao_message(d: &Dispatch, flight_number: Option<&str>, registration: Option<&str>, out: &Path) -> Result<u64> {
    write_file(out, &icao_message(d, flight_number, registration))
}

// ---------------------------------------------------------------------------------
// The whole Dispatch, as JSON.
// ---------------------------------------------------------------------------------

pub fn json(d: &Dispatch) -> Result<String> {
    Ok(serde_json::to_string_pretty(d)?)
}

pub fn write_json(d: &Dispatch, out: &Path) -> Result<u64> {
    write_file(out, &json(d)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ofp::fixtures;

    #[test]
    fn the_pln_is_well_formed_xml_with_every_waypoint() {
        let d = fixtures::sample();
        let out = pln(&d);
        assert!(out.starts_with("<?xml"));
        assert!(out.contains(&format!("<DepartureID>{}</DepartureID>", d.route.origin.icao)));
        assert!(out.contains(&format!("<DestinationID>{}</DestinationID>", d.route.destination.icao)));
        assert_eq!(out.matches("<ATCWaypoint id=").count(), d.route.points.len());
        assert_eq!(out.matches("</SimBase.Document>").count(), 1);
    }

    #[test]
    fn the_fms_names_every_point_and_counts_them_right() {
        let d = fixtures::sample();
        let out = fms(&d);
        assert!(out.starts_with("I\n1100 Version\n"));
        assert!(out.contains(&format!("NUMENR {}\n", d.route.points.len())));
        assert!(out.contains(&format!("ADEP {}", d.route.origin.icao)));
        assert!(out.contains(&format!("ADES {}", d.route.destination.icao)));
        // The waypoint rows are every line after NUMENR; the header carries its own
        // digit-leading line ("1100 Version") that a naive digit-prefix count would catch.
        let after_numenr: Vec<&str> = out.lines().skip_while(|l| !l.starts_with("NUMENR")).skip(1).collect();
        assert_eq!(after_numenr.len(), d.route.points.len());
        for w in &d.route.points {
            assert!(out.contains(&w.ident), "{} missing from the .fms", w.ident);
        }
    }

    #[test]
    fn the_rte_names_the_ends_and_the_alternate() {
        let d = fixtures::sample();
        let out = rte(&d);
        assert!(out.contains(&format!("ORIGIN {}", d.route.origin.icao)));
        assert!(out.contains(&format!("DEST {}", d.route.destination.icao)));
        if let Some(alt) = &d.alternate {
            assert!(out.contains(&format!("ALTN {}", alt.destination.icao)));
        }
    }

    #[test]
    fn the_icao_message_opens_and_closes_correctly_and_carries_the_callsign() {
        let d = fixtures::sample();
        let msg = icao_message(&d, Some("TAP123"), Some("CS-TVA"));
        assert!(msg.starts_with("(FPL-TAP123-IG"));
        assert!(msg.trim_end().ends_with(')'));
        assert!(msg.contains(&d.route.origin.icao));
        assert!(msg.contains(&d.route.destination.icao));
        assert!(msg.contains("REG/CSTVA"));
    }

    #[test]
    fn wake_category_follows_mtow() {
        assert_eq!(wake_category(300_000.0), 'H');
        assert_eq!(wake_category(78_000.0), 'M');
        assert_eq!(wake_category(2_000.0), 'L');
    }

    #[test]
    fn the_json_export_round_trips_through_serde() {
        let d = fixtures::sample();
        let text = json(&d).unwrap();
        let back: Dispatch = serde_json::from_str(&text).unwrap();
        assert_eq!(back.route.origin.icao, d.route.origin.icao);
        assert_eq!(back.spec.icao_type, d.spec.icao_type);
    }

    #[test]
    fn every_writer_creates_its_directory() {
        let dir = std::env::temp_dir().join(format!("ofp-export-{}", std::process::id()));
        let d = fixtures::sample();
        for (name, f) in [
            ("out.pln", &write_pln as &dyn Fn(&Dispatch, &Path) -> Result<u64>),
            ("out.fms", &write_fms),
            ("out.rte", &write_rte),
            ("out.json", &write_json),
        ] {
            let out = dir.join(name);
            let n = f(&d, &out).unwrap();
            assert!(out.is_file());
            assert_eq!(std::fs::metadata(&out).unwrap().len(), n);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }
}
